// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_bar_frag
#define  TXT_HEADER_bar_frag


const char bar_frag [] =
"#version 330\n"
"\n"
"layout(location = 0) out vec4 FragColor;\n"
"flat in vec3 color;\n"
"void main() {\n"
"  FragColor = vec4(color, 1);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_bar_frag
