// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_cloud_vert
#define  TXT_HEADER_cloud_vert


const char cloud_vert [] =
"#version 330\n"
"\n"
"layout(location = 0) in vec3 vertex_position;\n"
"\n"
"uniform mat4 projection_matrix;\n"
"uniform mat4 view_matrix;\n"
"uniform ivec2 viewport;\n"
"uniform float point_size;\n"
"void main() {\n"
"  float fovy = 45;  // degrees\n"
"  float heightOfNearPlane = float(abs(viewport.y)) / (2.0 * tan(0.5 * fovy * 3.1415 / 180.0));\n"
"  mat4 mvp = projection_matrix * view_matrix;\n"
"  gl_Position = mvp * vec4(vertex_position, 1.0);\n"
"  gl_PointSize = (heightOfNearPlane * point_size) / gl_Position.w;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_cloud_vert
