// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_cloud_frag
#define  TXT_HEADER_cloud_frag


const char cloud_frag [] =
"#version 330\n"
"\n"
"layout(location = 0) out vec4 FragColor;\n"
"uniform vec4 color;\n"
"\n"
"void main() {\n"
"  FragColor = color;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_cloud_frag
