// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_dot_frag
#define  TXT_HEADER_dot_frag


const char dot_frag [] =
"#version 330\n"
"\n"
"layout(location = 0) out vec4 FragColor;\n"
"uniform vec4 color;\n"
"\n"
"void main() {\n"
"  float d = dot(gl_PointCoord - 0.5, gl_PointCoord - 0.5) * 4;\n"
"  if (d > 1) {\n"
"    discard;\n"
"  } else if (d > .9 && d < 1) {\n"
"    FragColor = vec4(0, 0, 0, 1);\n"
"  } else {\n"
"    FragColor = vec4(color.xyz, 1);\n"
"  }\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_dot_frag
