// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_phong_frag
#define  TXT_HEADER_phong_frag


const char phong_frag [] =
"#version 330\n"
"\n"
"layout(location = 0) out vec4 FragColor;\n"
"\n"
"// uniform mat4 mvp;\n"
"// uniform mat4 modelview_matrix;\n"
"// uniform mat3 normal_matrix;\n"
"\n"
"float shininess = 100.0;\n"
"\n"
"flat in vec3 color_ambient;\n"
"flat in vec3 color_diffuse;\n"
"vec3 color_specular = vec3(1, 1, 1);\n"
"\n"
"vec3 light_pos = vec3(100, 100, 100);\n"
"in vec3 normal;\n"
"in vec3 eye_vec;\n"
"\n"
"void main() {\n"
"  vec3 final_color = color_ambient;\n"
"\n"
"  vec3 N = normalize(normal);\n"
"  vec3 L = normalize(light_pos - eye_vec);\n"
"  vec3 E = normalize(-eye_vec);\n"
"\n"
"  float lambertTerm = dot(N, L);\n"
"\n"
"  if (lambertTerm > 0.0) {\n"
"    final_color += color_diffuse * lambertTerm;\n"
"    vec3 R = reflect(-L, N);\n"
"    float specular = pow(max(dot(R, E), 0.0), shininess);\n"
"    final_color += color_specular * specular;\n"
"  }\n"
"\n"
"  FragColor = vec4(final_color, 1);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_phong_frag
