// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_phong_vert
#define  TXT_HEADER_phong_vert


const char phong_vert [] =
"#version 330\n"
"\n"
"layout(location = 0) in vec3 vertex_position;\n"
"layout(location = 1) in vec3 vertex_normal;\n"
"layout(location = 2) in vec3 vertex_color_ambient;\n"
"layout(location = 3) in vec3 vertex_color_diffuse;\n"
"layout(location = 4) in mat4 model_matrix;\n"
"\n"
"uniform mat4 projection_matrix;\n"
"uniform mat4 view_matrix;\n"
"\n"
"flat out vec3 color_ambient;\n"
"flat out vec3 color_diffuse;\n"
"flat out vec3 color_specular;\n"
"out vec3 normal;\n"
"out vec3 eye_vec;\n"
"void main() {\n"
"  mat4 modelview = view_matrix * model_matrix;\n"
"  mat4 mvp = projection_matrix * modelview;\n"
"  // mat3 normalmatrix = inverse(transpose(mat3(modelview)));;\n"
"\n"
"  gl_Position = mvp * vec4(vertex_position, 1.0);\n"
"  normal = normalize(mat3(modelview) * vertex_normal);\n"
"  eye_vec = vec3(modelview * vec4(vertex_position, 1.0));\n"
"\n"
"  color_ambient = vertex_color_ambient;\n"
"  color_diffuse = vertex_color_diffuse;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_phong_vert
