// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_sphere_frag
#define  TXT_HEADER_sphere_frag


const char sphere_frag [] =
"#version 330\n"
"\n"
"layout(location = 0) out vec4 FragColor;\n"
"uniform vec4 color;\n"
"\n"
"void main() {\n"
"  const vec3 lightDir = vec3(0.577, 0.577, 0.577);\n"
"  vec3 N;\n"
"  N.xy = gl_PointCoord.xy - 0.5;\n"
"\n"
"  float mag = dot(gl_PointCoord - 0.5, gl_PointCoord - 0.5);\n"
"\n"
"  if (mag > 0.25) {\n"
"    discard;\n"
"  } else {\n"
"    N.z = sqrt(1.0 - mag * 4);\n"
"    float diffuse = max(0.0, dot(lightDir, N));\n"
"    FragColor = vec4(color.xyz * diffuse, 1);\n"
"  }\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_sphere_frag
