// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_text_vert
#define  TXT_HEADER_text_vert


const char text_vert [] =
"#version 330\n"
"\n"
"layout(location = 0) in vec4 position;\n"
"out vec2 texCoords;\n"
"\n"
"void main(void) {\n"
"  gl_Position = vec4(position.xy, 0, 1);\n"
"  texCoords = position.zw;\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_text_vert
