// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_text_frag
#define  TXT_HEADER_text_frag


const char text_frag [] =
"#version 330\n"
"\n"
"uniform sampler2D tex;\n"
"uniform vec3 color;\n"
"\n"
"in vec2 texCoords;\n"
"out vec4 fragColor;\n"
"\n"
"void main(void) {\n"
"  fragColor = vec4(color, texture(tex, texCoords).r);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_text_frag
